
spring:
  config:
    import: optional:file:.env[.properties] #.env파일을 optional로 읽어와서 yml에 주입하는 명령어
  profiles:
    active: local #빌드된 jar실행시 local로 (on-profile:local 이런것들 작동시키기위해) #배포시 에는 .ebextention_dev/00-makeFiles.config에서 develop으로 실행하게 덮어씌움
                  #이로 인해 eb에서 .ebextention makefile에서 실행 설정값인 develop으로 실행 아무런설정없으면 (로컬환경) 실행이 local로 되는 효과

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_REST_API_KEY}
            #client-secret: ${KAKAO_CLIENT_SECRET}
            #redirect-uri: http://localhost:3000/login/oauth2/code/kakao
            redirect-uri : https://lte-frontend.netlify.app/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  servlet: #로컬 8080 톰캣서버 설정 (내부 80포트로 들어오는건 nginx가 설정, 외부애서 접근하는 80포트는 로드벨런서가)
          #외부 도메인 80포트 접근-> 로드벨런서가 내부 80포트로 토스-> nginx가 내부 80800포트로 토스
    multipart:
      enabled: true
      max-file-size: 50MB   #내부 8080포트 톰캣서버 멀티 파트 파일 50메가 제한
      max-request-size: 50MB

#JWT
jwt:
  secret: ${JWT_SECRET}
  access-exp-ms: ${JWT_EXPIRATION:3600000}
  refresh-exp-ms: ${JWT_REFRESH_EXPIRATION:1209600000}

#youtube
youtube:
  api-key: ${YOUTUBE_API_KEY}
  api-base: https://www.googleapis.com/youtube/v3

#s3
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region: ${AWS_REGION}
    s3:
      bucket: ${AWS_BUCKET}
      path:
        location: user/ #S3 저장될 디렉토리 세팅
server:
  port: ${PORT:8080} #톰캣서버 포트 8080으로 오픈
  tomcat:
    max-swallow-size: -1 #요청 사이즈 제한 없음
    max-http-form-post-size: -1 #http 요청 사이즈 제한 없음

#Swagger
springdoc:
  api-docs:
    path: /v3/api-docs

  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    operations-sorter: method

---

# local profile
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
      use_sql_comments: true
      default_batch_fetch_size: 1000

---

# develop profile
spring:
  config:
    activate:
      on-profile: develop
  datasource:
    url: ${AWS_DB_URL}
    username: ${AWS_DB_USERNAME}
    password: ${AWS_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      use_sql_comments: true
      default_batch_fetch_size: 1000




