
spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: local

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_REST_API_KEY}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

#JWT
JWT_SECRET: ${JWT_SECRET}
JWT_EXPIRATION: ${JWT_EXPIRATION}                  # Access(ms)
JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION}  # Refresh(ms)

#s3
cloud:
  aws:
    access-key: ${AWS_ACCESS_KEY:default-access-key}
    secret-key: ${AWS_SECRET_KEY:default-secret-key}
    region: ${AWS_REGION:ap-northeast-2}
    bucket: ${AWS_BUCKET:default-bucket}

server:
  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: -1

#Swagger
springdoc:
  api-docs:
    path: /v3/api-docs
    # Swagger? OpenAPI ??? ???? ?? ??
  swagger-ui:
    path: /swagger-ui.html
    # Swaggerd UI ??? URL ?? ??
    display-request-duration: true # ??? ???? ? ?? ?? ?? ??
    operations-sorter: method # ??? ?? ???? API ??---

---

# local profile
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
      use_sql_comments: true
      default_batch_fetch_size: 1000

---

# develop profile
spring:
  config:
    activate:
      on-profile: develop
  datasource:
    url: ${AWS_DB_URL}
    username: ${AWS_DB_USERNAME}
    password: ${AWS_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
      use_sql_comments: true
      default_batch_fetch_size: 1000




